# -*- coding: utf-8 -*-
"""REINVENT_V1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWeO3EW6eqyKmIZnJINLDbC4eCrubm7q
"""

!pip install -q condacolab
import condacolab
condacolab.install()
!conda create -n reinvent python=3.6 -y
!conda run -n reinvent conda install -c rdkit rdkit -y
!conda run -n reinvent pip install scikit-learn tqdm pexpect

!conda run -n reinvent pip install ./torch-0.1.12.post2-cp36-cp36m-linux_x86_64.whl

!conda run -n reinvent python -c "import torch; print(torch.__version__)"
!conda run -n reinvent python -c "import sklearn; print(sklearn.__version__)"
!conda run -n reinvent conda list rdkit
!conda run -n reinvent python --version

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/MarcusOlivecrona/REINVENT.git
# %cd REINVENT

!git checkout v1.0.1

!wget -q https://github.com/MarcusOlivecrona/REINVENT/releases/download/v1.0.1/saved_models.tar.gz
!wget -q https://github.com/MarcusOlivecrona/REINVENT/releases/download/v1.0.1/data.tar.gz

!tar -xzf saved_models.tar.gz
!tar -xzf data.tar.gz
!ls -R

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/MarcusOlivecrona/REINVENT.git
# %cd REINVENT

!ls

!conda run -n reinvent python -c "import pandas as pd; df = pd.read_csv('/content/250k_rndm_zinc_drugs_clean_3_TPSA.csv'); print(df)"
!conda run -n reinvent python -c "import pandas as pd; df = pd.read_csv('/content/250k_rndm_zinc_drugs_clean_3_TPSA.csv'); print(df.columns)"

!conda run -n reinvent python -u data_structs.py /content/250k_rndm_zinc_drugs_clean_3_TPSA.csv

!conda run --no-capture-output -n reinvent python -u train_prior.py

!conda run -n reinvent python -u main.py --scoring-function tanimoto --num-steps 5 --batch-size 10

!conda run -n reinvent python -u main.py --scoring-function tanimoto --scoring-function-kwargs query_structure "CC(=O)OC1=CC=CC=C1C(=O)O" --num-steps 5 --batch-size 10

# sampling is done via the Prior inside main/train scripts; a quick way is to run a tiny RL loop

for i in range(5):
  !conda run -n reinvent python -u main.py --scoring-function LogP_TPSA_AdaptiveScore --scoring-function-kwargs w_logp 0.5 w_tpsa 0.5 ema_alpha 0.05 --num-steps 5 --batch-size 10

